text_snippets = [
    "Searching alien spaceships.",
    "Looking for it under the table.",
    "Opening ancient jars.",
    "Exploring lost civilizations.",
    "Scanning the wreckage of Titanic.",
    "Examining egyptian hieroglyphs.",
    "Penetrating space-time.",
    "Digging up ancient gold.",
    "Discovering cave paintings.",
    "Chasing ponies in dreams.",
    "Detecting life on distant planets.",
    "Absorbing infinite wisdom.",
    "Studying UFO footages.",
    "Memorizing useless information.",
    "Generating sudoku game.",
    "Decrypting passwords.",
    "Entering wardrobes.",
    "Traveling far to return the ring.",
    "These are not the droids you are looking for.",
    "A long time ago in a galaxy far, far away...",
    "Landing on the Moon",
    "Putting pineapples on pizzas.",
    "Asking too many questions.",
    "Untwisting baloon animals.",
    "Closing elevator door.",
    "Who let the dogs out?",
    "What is love? (baby don't hurt me)",
    "Never gonna give you up...",
    "Never gonna let you down...",
    "I'll be back!",
    "To infinity and beyond!",
    "Eating spaghsetti with a spoon.",
    "Shaking hands with Bigfoot.",
]