"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['sudoku_game.py']
DATA_FILES = ["colors.py", 
              "sudoku_map.py", 
              "text.py", 
              "valid_maps.txt",
              "resources/"
]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
